name: build-and-push-guess-app
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Show go version
        run: go version
       
      - name: Install windows compiler
        run: sudo apt-get install gcc-mingw-w64

      - name: Print working directory
        run: pwd

      - name: Create artifact directory
        run: mkdir ~/artifact
      
      - name: Install MinGW-w64
        run: sudo apt update && sudo apt install -y mingw-w64

      - name: Compile for Windows x64
        run: |
          x86_64-w64-mingw32-gcc -o my_program.exe main.c

      - name: Show build
        run: ls -l ~/artifact

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifact.exe
        