name: build-and-push-guess-app
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from git repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Show go version
        run: go version

      - name: Print working directory
        run: pwd

      - name: Build for windows
        run: go build -o artifacts/guess_app_windows_amd64.exe
        env:
          GOOS: windows
          GOARCH: amd64

      - name: Build for linux
        run: go build -o artifacts/guess_app_linux_amd64
        env:
          GOOS: linux
          GOARCH: amd64
      
      - name: Build for darwin (macOS)
        run: go build -o artifacts/guess_app_darwin_arm64
        env:
          GOOS: darwin
          GOARCH: arm64
      
      - name: Show artifacts
        run: ls -l artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: guess_app_artifacts
          path: artifacts